def shared
    pod 'ConstraintDSL', :path => '../'
end

target 'ConstraintDSL_Example' do
    use_frameworks!
    shared
end

target 'ConstraintDSL_Tests' do
    shared
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.2'
end
