use_frameworks!

target 'ConstraintDSL_Example' do
  pod 'ConstraintDSL', :path => '../'

  target 'ConstraintDSL_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
